services:
  - type: web
    name: ai-groundwater-management
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements-minimal.txt
    startCommand: gunicorn main_app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.18
